/**
 * RUX Prompts — Storage and RevenueCat proxy service code generators
 */

export function buildStorageServiceCode(): string {
  return `
// Storage — file uploads, listing, deletion (presigned URL flow)
export const storage = {
  getUploadUrl: async (filename: string, contentType: string, size: number, isPublic?: boolean) => {
    try {
      const res = await fetch(\`\${API_BASE}/api/proxy/storage\`, {
        method: 'POST', headers,
        body: JSON.stringify({ filename, contentType, size, isPublic })
      });
      const result = await res.json().catch(() => ({}));
      if (!res.ok) {
        const message =
          typeof result?.error === 'string'
            ? result.error
            : result?.error?.message || result?.message || 'Failed to get upload URL';
        throw new Error(message);
      }
      return result; // { uploadUrl, fileUrl, fileId, expiresAt }
    } catch (error) {
      console.error('Storage getUploadUrl error:', error);
      throw error;
    }
  },
  upload: async (filename: string, contentType: string, fileData: Blob | ArrayBuffer) => {
    try {
      // Step 1: Get presigned upload URL
      const size = fileData instanceof Blob ? fileData.size : fileData.byteLength;
      const urlResult = await storage.getUploadUrl(filename, contentType, size, true);
      // Step 2: Upload file directly to storage
      await fetch(urlResult.uploadUrl, {
        method: 'PUT',
        headers: { 'Content-Type': contentType },
        body: fileData,
      });
      return { fileUrl: urlResult.fileUrl, fileId: urlResult.fileId };
    } catch (error) {
      console.error('Storage upload error:', error);
      throw error;
    }
  },
  list: async (prefix?: string, limit?: number) => {
    try {
      const params = new URLSearchParams();
      if (prefix) params.set('prefix', prefix);
      if (limit) params.set('limit', String(limit));
      const res = await fetch(\`\${API_BASE}/api/proxy/storage?\${params.toString()}\`, {
        method: 'GET',
        headers: { 'X-RUX-API-Key': API_KEY },
      });
      return res.json(); // { files: [...], nextCursor, totalCount }
    } catch (error) {
      console.error('Storage list error:', error);
      return { files: [] };
    }
  },
  delete: async (fileId: string) => {
    try {
      const res = await fetch(\`\${API_BASE}/api/proxy/storage\`, {
        method: 'DELETE',
        headers,
        body: JSON.stringify({ fileId })
      });
      return res.json();
    } catch (error) {
      console.error('Storage delete error:', error);
      throw error;
    }
  }
};`;
}

/**
 * Build RevenueCat payments service code for mobile apps (iOS/Android)
 * This is injected as a separate src/services/payments.ts file
 */
export function buildRevenueCatServiceCode(): string {
  return `// RevenueCat Payments Service (Mobile)
// Auto-generated by Rulxy — do not edit
import Purchases, { PurchasesOfferings, PurchasesPackage, CustomerInfo } from 'react-native-purchases';

const RC_API_KEY = process.env.EXPO_PUBLIC_REVENUECAT_API_KEY || 'YOUR_REVENUECAT_API_KEY';

export const initPayments = async () => {
  try {
    Purchases.setLogLevel(Purchases.LOG_LEVEL.DEBUG);
    Purchases.configure({ apiKey: RC_API_KEY });
  } catch (error) {
    console.error('Failed to initialize payments:', error);
  }
};

export const payments = {
  getOfferings: async (): Promise<PurchasesOfferings | null> => {
    try {
      const offerings = await Purchases.getOfferings();
      return offerings;
    } catch (error) {
      console.error('Failed to get offerings:', error);
      return null;
    }
  },

  purchase: async (pkg: PurchasesPackage): Promise<CustomerInfo | null> => {
    try {
      const { customerInfo } = await Purchases.purchasePackage(pkg);
      return customerInfo;
    } catch (error: any) {
      if (!error.userCancelled) {
        console.error('Purchase failed:', error);
      }
      return null;
    }
  },

  getCustomerInfo: async (): Promise<CustomerInfo | null> => {
    try {
      const info = await Purchases.getCustomerInfo();
      return info;
    } catch (error) {
      console.error('Failed to get customer info:', error);
      return null;
    }
  },

  checkEntitlement: async (entitlementId: string): Promise<boolean> => {
    try {
      const info = await Purchases.getCustomerInfo();
      return info.entitlements.active[entitlementId] !== undefined;
    } catch (error) {
      console.error('Failed to check entitlement:', error);
      return false;
    }
  },

  restorePurchases: async (): Promise<CustomerInfo | null> => {
    try {
      const info = await Purchases.restorePurchases();
      return info;
    } catch (error) {
      console.error('Failed to restore purchases:', error);
      return null;
    }
  },
};
`;
}
